# Supervisor configuration
[supervisor]
max_agents = 10
monitor_interval_secs = 5
web_port = 8080
enable_dashboard = true
log_level = "info"

[supervisor.alerts]
max_cpu_percent = 80.0
max_memory_mb = 512
max_tool_calls_per_minute = 100
suspicious_patterns = [
    "rm -rf",
    "curl | sh",
    "wget | bash",
    "/etc/passwd",
    "/etc/shadow",
    "sudo",
    "chmod 777",
    "nc -e",
    "bash -i"
]

# Agent spawn defaults
[supervisor.agent_defaults]
sandbox_mode = "Moderate"
max_runtime_hours = 24
auto_restart = false
restart_delay_secs = 60

# Resource monitoring
[supervisor.monitoring]
collect_metrics = true
metrics_retention_days = 7
alert_retention_days = 30
event_retention_days = 14

# Security policies
[supervisor.security]
require_sandbox = true
allow_network_access = true
max_file_operations_per_minute = 1000
max_network_requests_per_minute = 100

# Notification settings (optional)
[supervisor.notifications]
enabled = false
webhook_url = ""
email_to = ""
alert_threshold = "high"  # low, medium, high, critical