# Minimal supervisor configuration for testing
max_agents = 5
monitor_interval_secs = 10
web_port = 8080
enable_dashboard = true
log_level = "info"

[alerts]
max_cpu_percent = 80.0
max_memory_mb = 512
max_tool_calls_per_minute = 100
suspicious_patterns = ["rm -rf", "curl | sh", "/etc/passwd"]