# Test agent 2 configuration - Mock LLM with different settings
database_path = "/data/test_agent_2.db"

[llm]
provider = "mock"
model = "mock-model-2"

[[mcp_servers]]
name = "filesystem"
transport = "stdio"
command = "npx"
args = ["-y", "@modelcontextprotocol/server-filesystem", "/workspace"]