name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Nix
      uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
    
    - name: Setup Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-
    
    - name: Check formatting
      run: nix develop -c cargo fmt -- --check
    
    - name: Run clippy
      run: nix develop -c cargo clippy -- -D warnings
    
    - name: Run tests
      run: nix develop -c cargo test --verbose
    
    - name: Build
      run: nix develop -c cargo build --verbose --release
    
    - name: Build musl binary
      continue-on-error: true
      run: |
        echo "Building musl target..."
        export RUSQLITE_BUNDLED=1
        nix develop -c cargo build --release --target x86_64-unknown-linux-musl
    
    - name: Show binary info
      run: |
        echo "=== Regular release binary ==="
        echo "Binary size: $(du -h target/release/replicante | cut -f1)"
        file target/release/replicante
        echo ""
        if [ -f target/x86_64-unknown-linux-musl/release/replicante ]; then
          echo "=== Musl binary ==="
          echo "Binary size: $(du -h target/x86_64-unknown-linux-musl/release/replicante | cut -f1)"
          file target/x86_64-unknown-linux-musl/release/replicante
          ldd target/x86_64-unknown-linux-musl/release/replicante 2>&1 | head -5 || true
        else
          echo "Musl binary not built (expected due to SQLite linking issues)"
        fi